name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      -
        name: Set RELEASE_TAG env
        run: echo RELEASE_TAG=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --release-notes=changelog/${{ env.RELEASE_TAG }}.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_PAT: ${{ secrets.HOMEBREW_PAT }}
          HOMEBREW_ORG: ${{ secrets.HOMEBREW_ORG }}
          HOMEBREW_REPO: ${{ secrets.HOMEBREW_REPO }}
          HOMEBREW_COMMIT_NAME: ${{ secrets.HOMEBREW_COMMIT_NAME }}
          HOMEBREW_COMMIT_EMAIL: ${{ secrets.HOMEBREW_COMMIT_EMAIL }}
